# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Aniket Nagrale 
title: Product Analyst
email: aniketn.iitkgp@gmail.com
# website: www.github.com/sproogen/resume-theme
darkmode: true

# Social links
# twitter_username: facespics
github_username:  aniketnagrale 
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: aniketnagrale.in
linkedin_username: aniketnagrale
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Structured problem solver and result oriented professional with experience in managing a team of software, cloud & machine learning engineers, proven ability to deliver great solutions, worked on deploying machine learning workflows in production and analyzing data to make informed trade-offs.
  
  Hold a strong engineering background after being graduated from the Indian Institute of Technology, Kharagpur, where I got immense opportunities to learn and hone my skills & interests in practice.
  
# I am most skilled in:  <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
educaton_title: B.Tech from Indian Institute of Technology, Kharagpur

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Product Engineering & Management, some of my other interests and hobbies are:
   - Reading
   - Gaming
   - Cricket & Basketball

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
